name: EC2 Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
          -i private_key.pem \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          cd ~/studentdeploy-pro
          git pull origin main
          python3 app.py

          EOF